#!/usr/bin/env node
/**
 * Build the browser bundle.
 *
 * There is no bundler dependency on purpose (the reference plugins on this
 * host ship a hand-written single-file bundle): the build is a deterministic
 * import-stripping concatenation of src/ into the __ModuleLoader__ template.
 * Determinism matters — `--check` re-runs the same transform and fails when
 * lib/client.js is stale, so a committed bundle can never drift from source.
 *
 * Usage:
 *   node scripts/build.mjs           # write lib/client.js
 *   node scripts/build.mjs --check   # fail (exit 1) when lib/client.js is stale
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const SRC = join(root, 'src')
const OUT = join(root, 'lib', 'client.js')

/** Dependency-safe order; every module lands in one IIFE scope. */
const MODULES = [
  'params.js',
  'host-hooks.js',
  'store.js',
  'effects/quantize.js',
  'effects/fluid-shaders.js',
  'effects/sources.js',
  'effects/fluid.js',
  'effects/grid.js',
  'effects/particles.js',
  'effects/spotlight.js',
  'effects/glass.js',
  'effects/layers.js',
  'effects/interaction.js',
  'theme-layer.js',
  'settings-row.js',
  'api.js',
  'apply.js',
]

/** Remove `import ... from '...'` statements (single- and multi-line). */
function stripImports(source) {
  return source.replace(/^import\s+[\s\S]*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, '')
}

/** Turn `export const/function/class` into plain declarations and drop re-exports. */
function stripExports(source) {
  return source
    .replace(/^export\s+\{[^}]*\}\s*;?\s*$/gm, '')
    .replace(/^export\s+(?=(?:const|let|var|function|class|async)\b)/gm, '')
}

function transform(relative) {
  const source = readFileSync(join(SRC, relative), 'utf8')
  const body = stripExports(stripImports(source)).trim()
  return `// ─────────────────────────────────────────────────────────────────────────────\n// src/${relative}\n// ─────────────────────────────────────────────────────────────────────────────\n${body}\n`
}

/**
 * Every module lands in ONE IIFE scope, so two files declaring the same
 * top-level name is a hard `SyntaxError: Identifier 'x' has already been
 * declared` in the browser — and a bundler-less build has nothing that would
 * notice. This check does: it fails the build with the offending files listed.
 */
function findCollisions() {
  const owner = new Map()
  const collisions = []
  for (const relative of MODULES) {
    const source = stripExports(stripImports(readFileSync(join(SRC, relative), 'utf8')))
    const names = new Set()
    for (const match of source.matchAll(/^(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm)) {
      names.add(match[1])
    }
    for (const name of names) {
      if (owner.has(name)) collisions.push({ name, first: owner.get(name), second: relative })
      else owner.set(name, relative)
    }
  }
  return { collisions, total: owner.size }
}

function build() {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
  const template = readFileSync(join(SRC, 'client.template.js'), 'utf8')
  const banner = `/*!\n * ${pkg.name} v${pkg.version} — client bundle (GENERATED by scripts/build.mjs; edit src/ instead).\n *\n * DeepSeek 官网视觉语言的 DSH Web 主题：毛玻璃 / 液化(流体) / 量子化(Q1-Q4)。\n *\n * Third-party code is MIT/Apache-2.0 and attributed per file; see REUSE.md and LICENSES/.\n * Ported in part from:\n *   JohnnyTing/dsh-official-homepage-theme (MIT)  — fluid shaders, elastic grid, pointer field\n *   ycqaq233/dsh-unknown-theme          (MIT)  — glass values, spotlight, particle morph, whale path\n *   RevolutionLA/dsh-dream-skin         (MIT)  — @supports glass gate, host file API shape\n *   mux9056-bot/dsh-theme               (Apache-2.0) — slot registration, ctx.provide pattern\n *   hughsk/glsl-dither                  (MIT)  — Bayer 4x4 matrix\n *   yushi-xxh/dsh-homepage-skin         (MIT)  — WebGL teardown discipline\n */\n`
  const bundle = MODULES.map(transform).join('\n')
  const out = template
    .replace('/*__BUNDLE__*/', bundle)
    .replace('__VERSION__', pkg.version)
  return `${banner}${out}`
}

const check = process.argv.includes('--check')
const { collisions, total } = findCollisions()
if (collisions.length > 0) {
  console.error(`✘ ${collisions.length} 个顶层标识符在模块间重名（合并进同一作用域会直接 SyntaxError）：`)
  for (const c of collisions) console.error(`   - ${c.name}: ${c.first} ↔ ${c.second}`)
  console.error('   改掉其中一个（加模块前缀）后重新构建。')
  process.exit(1)
}
const next = build()

if (check) {
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {
    console.error('✘ lib/client.js is missing — run: node scripts/build.mjs')
    process.exit(1)
  }
  if (current !== next) {
    console.error('✘ lib/client.js is STALE — run: node scripts/build.mjs')
    process.exit(1)
  }
  const lines = next.split('\n').length
  console.log(`✔ lib/client.js is up to date (${lines} lines, ${Buffer.byteLength(next)} bytes)`)
  process.exit(0)
}

writeFileSync(OUT, next)
const lines = next.split('\n').length
console.log(`✔ wrote lib/client.js (${lines} lines, ${Buffer.byteLength(next)} bytes) from ${MODULES.length} modules`)
